Train 0/200
<torch.utils.data.dataloader.DataLoader object at 0x000002ABD98F0D60> <torch.utils.data.dataloader.DataLoader object at 0x000002ABD98F0DF0>
Traceback (most recent call last):
  File "D:\challege_ai\baseline\train.py", line 141, in <module>
    trainer.train(train_l_loader=train_l_loader, train_u_loader=train_u_loader)
  File "D:\challege_ai\baseline\modules\trainer.py", line 54, in train
    train_l_data, train_l_label = train_l_dataset.next()
  File "C:\Users\rudwn\anaconda3\envs\deeplearning\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "C:\Users\rudwn\anaconda3\envs\deeplearning\lib\site-packages\torch\utils\data\dataloader.py", line 569, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "C:\Users\rudwn\anaconda3\envs\deeplearning\lib\site-packages\torch\utils\data\dataloader.py", line 521, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "C:\Users\rudwn\anaconda3\envs\deeplearning\lib\site-packages\torch\utils\data\sampler.py", line 226, in __iter__
    for idx in self.sampler:
  File "C:\Users\rudwn\anaconda3\envs\deeplearning\lib\site-packages\torch\utils\data\sampler.py", line 118, in __iter__
    yield from torch.randint(high=n, size=(32,), dtype=torch.int64, generator=generator).tolist()
RuntimeError: random_ expects 'from' to be less than 'to', but got from=0 >= to=0